# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

source 'https://github.com/SPHTech-Mobile/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SPHUIKit/SPHPopup', '2.0.1'
  pod 'SPHUIKit/SPHProgressButton', '2.0.1'
  pod 'SPHUIKit/SPHScrollableMenuView', '2.0.1'
  pod 'Teleport', '1.5.0'
  pod 'Tagger', '3.4.1'
  pod 'TargetExtension', '1.1.3'
  pod 'Flagpole/FlagpoleFirebase', '1.3.0'
  pod 'SwiftMessages', '~> 7.0'
  pod 'lottie-ios'
  # Use separate branch for reskin epic.
  # TODO: In Tambourine, decouple business logic from UI so we can input our own custom UI for mini and large radio players
  # This commit contains the re skin, BBC integration support, share completion block, resume time added with zero support, remove spinner on like button, mini and expanded player image changed to aspect fit
  pod 'Tambourine', :git => 'git@github.com:SPHTech-Mobile/Tambourine.git', :commit => 'f396178437087d7a9164e152efb7d0a0e0e94ba4'
  pod 'NetworkOperationQueue', '1.2.4'
  pod 'Thesaurus', '2.2.4'

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
